# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Theme Settings
remote_theme: hydecorp/hydejack@v9.0.5

# Site Settings
title: CodeThatMath
lang: en
description: Explore complex topics through practice and common sense
url: https://codethatmath.com
baseurl: ''
copyright: Â© 2021. All rights reserved.

accent_image: "hero.png"
#accent_image: https://codethatmath.s3.eu-central-1.amazonaws.com/style-images/hero-blackTriangles.png
accent_color: rgb(103,107,254) 


font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Lato, Helvetica, Arial, sans-serif
google_fonts: Lato:00|Noto+Sans:400,400i,700,700i

author:
  name:  Alexander Shamanskiy
  email: shamanskiy@codethatmath.com
  #picture:  https://codethatmath.s3.eu-central-1.amazonaws.com/autor_image.jpg
  social:
    github: shamanskiy
    linkedin: shamanskiy
    researchgate: Alexander_Shamanskiy
    email: shamanskiy@codethatmath.com

google_analytics: UA-179576532-1

defaults:
  - scope:
      type: posts
    values:
      comments: true
      invert_sidebar: true

menu:
  - title: All posts
    url:   /posts/
  - title: About
    url:   /about/

legal:
  - title: Disclaimer
    url:  /disclaimer/
#  - title: Cookies Policy
#    url:  /about/

paginate:      10
paginate_path: '/:num/'




# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
